tasks:
  - init: |
      pyenv install 3.10.12  # Specify the Python version you need
      pyenv global 3.10.12   # Set the Python version globally
      pip install -r requirements.txt
    command: flask init && flask run

ports:
  - port: 8080
    onOpen: open-browser
    visibility: public
image:
  file: .gitpod.Dockerfile

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    addCheck: true
    addComment: true
